[bugfix]YOLOXLrUpdaterHook conflict (#169)
* bugfix: YOLOXLrUpdaterHook conflict
KeyError: 'YOLOXLrUpdaterHook is already registered in hook'
KeyError: 'YOLOXLrUpdaterHook is not in the hook registry'